Dev/1.0
hms-networks/sc-flexy-retry-lib pull request #1
Opened 2021-02-16 21:58 UTC by alexjhawk

2021-02-16 22:01 UTC, alexjhawk commented
An implementation of each of the three abstract classes can be found in my test class at https://github.com/hms-networks/sc-flexy-retry-lib/blob/test/1.0/src/test/java/com/hms_networks/americas/sc/retry/test/AutomaticRetryTestMain.java

2021-02-17 14:08 UTC, TomKimsey requested changes
I would expect some users would want a constant retry algorithm (ie retry after 5 seconds every time it fails. 

Also you should probably add the github actions to this pr so that code style is verified.

Why was the decision made to implement abstract classes which a user has to implement rather than just passing a user written method as a callable or some other 1.4 friendly way? In doing that the user doesnt need to implement anything on the library side.

2021-02-17 14:08 UTC, TomKimsey commented on README.md
> +None
```suggestion

None
```

2021-02-17 14:08 UTC, TomKimsey commented on README.md
> +None
For consistency

2021-02-17 14:29 UTC, alexjhawk commented on README.md
> +None
fixed

2021-02-17 14:35 UTC, alexjhawk commented
> I would expect some users would want a constant retry algorithm (ie retry after 5 seconds every time it fails.
> 
> Also you should probably add the github actions to this pr so that code style is verified.
> 
> Why was the decision made to implement abstract classes which a user has to implement rather than just passing a user written method as a callable or some other 1.4 friendly way? In doing that the user doesnt need to implement anything on the library side.

- Users can implement that using the standard AutomaticRetryCode.java class. They can specify the delay in the return value of getDelayMillisBeforeRetry(). Additionally, they would need to implement the code() method and the getMaxRetries() method. 
- GitHub actions have been added
- The decision was made to use abstract classes because it is a simple way to provide the setState() method which is integral in order to allow for proper retry or critical stop depending on what occurs. Additionally, the Runnable class in Java 1.4 is itself an abstract class and requires you to implement the method #run(). Our abstract class(es) are very similar, except that they add additional methods that determine the parameters of the retry algorithm.

2021-02-17 15:00 UTC, oliver-walker-hms requested changes

2021-02-17 15:00 UTC, oliver-walker-hms commented on src/main/java/com/hms_networks/americas/sc/retry/AutomaticRetryState.java
> +  /** Instance state integer */
missing period

2021-02-17 15:00 UTC, oliver-walker-hms commented on src/main/java/com/hms_networks/americas/sc/retry/AutomaticRetryResult.java
> +  /** Instance result integer */
Missing period

2021-02-17 15:04 UTC, alexjhawk commented on src/main/java/com/hms_networks/americas/sc/retry/AutomaticRetryState.java
> +  /** Instance state integer */
fixed/added

2021-02-17 15:04 UTC, alexjhawk commented on src/main/java/com/hms_networks/americas/sc/retry/AutomaticRetryResult.java
> +  /** Instance result integer */
fixed/added

2021-02-17 15:10 UTC, oliver-walker-hms approved these changes, later dismissed

2021-02-17 20:54 UTC, TomKimsey approved these changes, later dismissed

2021-02-17 21:13 UTC, it-hms approved these changes, later dismissed
I approve. My only recommendation is to change the name of _code_ method to something more verbose/specific like _retry_action_.

2021-02-17 21:47 UTC, alexjhawk commented
> I approve. My only recommendation is to change the name of _code_ method to something more verbose/specific like _retry_action_ ( or something better). I cannot think of a better name right now. hopefully you can.

I've updated the method named to #codeToRetry()

2021-02-17 22:27 UTC, it-hms approved these changes

2021-02-17 22:50 UTC, TomKimsey approved these changes

2021-02-18 13:23 UTC, oliver-walker-hms approved these changes

2021-02-18 13:23 UTC, merged